rules:
  - "DOMAIN-SUFFIX,github.com,🚀 代理"
  - "DOMAIN-SUFFIX,tinyurl.com,🚀 代理"
  - "DOMAIN-SUFFIX,rogueamoeba.net,🚀 代理"
  - "DOMAIN-SUFFIX,st.com,🚀 代理"

  - "RULE-SET,LocalAreaNetwork,🎯 全球直连"
  - "RULE-SET,BanAD,🛑 广告拦截"
  - "RULE-SET,BanProgramAD,🛑 广告拦截"
  - "RULE-SET,JuDirect,🎯 全球直连"
  - "RULE-SET,UnBan,🎯 全球直连"
  - "RULE-SET,Bilibili,🎯 全球直连"
  - "RULE-SET,BilibiliHMT,🎯 全球直连"
  - "RULE-SET,ChinaMedia,🎯 全球直连"
  - "RULE-SET,ProxyGFWlist,🚀 代理"
  - "RULE-SET,ChinaDomain,🎯 全球直连"
  - "RULE-SET,ChinaCompanyIp,🎯 全球直连"
  - "RULE-SET,Download,🎯 全球直连"
  - "RULE-SET,SteamCN,🎯 全球直连"
  - "RULE-SET,Bing,🎯 全球直连"
  - "RULE-SET,OneDrive,🎯 全球直连"
  - "RULE-SET,Microsoft,🎯 全球直连"
  - "RULE-SET,NetEaseMusic,🎯 全球直连"

  - "RULE-SET,Apple,🎯 全球直连"
  - "RULE-SET,GoogleFCM,🚀 代理"
  - "RULE-SET,GoogleCN,🚀 代理"
  - "RULE-SET,Telegram,🚀 代理"
  - "RULE-SET,OpenAi,🚀 代理"

  - "RULE-SET,Steam,🚀 代理"
  - "RULE-SET,Epic,🚀 代理"
  - "RULE-SET,Origin,🚀 代理"
  - "RULE-SET,Sony,🚀 代理"

  - "RULE-SET,Nintendo,🚀 代理"
  - "RULE-SET,YouTube,🚀 代理"
  - "RULE-SET,Netflix,🚀 代理"
  - "RULE-SET,Bahamut,🚀 代理"
  - "RULE-SET,ProxyMedia,🚀 代理"

  - "GEOIP,CN,🎯 全球直连"
  - "MATCH,🐟 漏网之鱼"
