rules:
  - "DOMAIN-SUFFIX,github.com,🚀 代理"
  - "DOMAIN-SUFFIX,tinyurl.com,🚀 代理"
  - "DOMAIN-SUFFIX,rogueamoeba.net,🚀 代理"
  - "DOMAIN-SUFFIX,st.com,🚀 代理"

  - "GEOSITE,private,🎯 全球直连"
  - "GEOSITE,category-ads-all,🛑 广告拦截"
  - "GEOSITE,microsoft@cn,🎯 全球直连"
  - "GEOSITE,apple-cn,🎯 全球直连"
  - "GEOSITE,steam@cn,🎯 全球直连"
  - "GEOSITE,bilibili,🎯 全球直连"
  - "GEOSITE,cn,🎯 全球直连"
  - "GEOSITE,google,🚀 代理"
  - "GEOSITE,youtube,🚀 代理"
  - "GEOSITE,telegram,🚀 代理"
  - "GEOSITE,netflix,🚀 代理"
  - "GEOSITE,openai,🚀 代理"
  - "GEOSITE,gfw,🚀 代理"
  - "GEOIP,telegram,🚀 代理"
  - "GEOIP,private,🎯 全球直连"
  - "GEOIP,CN,🎯 全球直连"
  - "MATCH,🎯 全球直连"