proxy-groups:
  - name: ğŸš€ ä»£ç†
    type: select
    proxies:
      - ğŸŒŸ æ‰‹å·¥ç²¾é€‰
      - ğŸ”§ æˆ‘çš„è§„åˆ™
      - ğŸª¬ æ‰‹åŠ¨åˆ‡æ¢
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - DIRECT
  - name: ğŸ”§ æˆ‘çš„è§„åˆ™
    include-all: true
    filter: (?i)ğŸŒŸ|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|France|æ³•å›½|Paris|Netherlands|GB
    type: select
  - name: ğŸŒŸ æ‰‹å·¥ç²¾é€‰
    include-all: true
    filter: (?i)ğŸŒŸ
    type: select
  - name: ğŸª¬ æ‰‹åŠ¨åˆ‡æ¢
    include-all: true
    type: select
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    include-all: true
    interval: 300
    tolerance: 100
  - name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - REJECT
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT

rule-providers:
  myreject:
    behavior: "domain"
    type: file
    format: text
    path: ./MyReject.txt
  mydirect:
    behavior: "domain"
    type: file
    format: text
    path: ./MyDirect.txt
  myproxy:
    behavior: "domain"
    type: file
    format: text
    path: ./MyProxy.txt

rules:
  # å»ºè®®æŠŠè‡ªå®šä¹‰è§„åˆ™æ”¾åœ¨æœ€ä¸Šæ–¹ï¼Œä¼˜å…ˆçº§æœ€é«˜
  - RULE-SET,myreject,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,mydirect,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,myproxy,ğŸš€ ä»£ç†

  # 1. æœ€é«˜ä¼˜å…ˆçº§ï¼šå±€åŸŸç½‘å’Œç‰¹æ®Šåœ°å€ç›´è¿ï¼Œé¿å…ä»£ç†å†²çª
  - "GEOSITE,private,ğŸ¯ å…¨çƒç›´è¿"
  - "GEOIP,private,ğŸ¯ å…¨çƒç›´è¿,no-resolve"

  # 3. å¹¿å‘Šæ‹¦æˆª
  - "GEOSITE,category-ads-all,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"

  # 4. å¿…é¡»ç›´è¿çš„ç‰¹å®šæœåŠ¡ (å¦‚å¾®è½¯/è‹¹æœ/Steamçš„ä¸­å›½åŒºCDN)
  - "GEOSITE,microsoft@cn,ğŸ¯ å…¨çƒç›´è¿"
  - "GEOSITE,apple-cn,ğŸ¯ å…¨çƒç›´è¿"
  - "GEOSITE,steam@cn,ğŸ¯ å…¨çƒç›´è¿"
  - "GEOSITE,bilibili,ğŸ¯ å…¨çƒç›´è¿"

  # 5. å¿…é¡»èµ°ä»£ç†çš„ç‰¹å®šæœåŠ¡
  - "GEOSITE,google,ğŸš€ ä»£ç†"
  - "GEOSITE,youtube,ğŸš€ ä»£ç†"
  - "GEOSITE,telegram,ğŸš€ ä»£ç†"
  - "GEOIP,telegram,ğŸš€ ä»£ç†"
  - "GEOSITE,netflix,ğŸš€ ä»£ç†"
  - "GEOSITE,openai,ğŸš€ ä»£ç†"

  # 6. è¢«å¢™ç½‘ç«™åˆ—è¡¨
  - "GEOSITE,gfw,ğŸš€ ä»£ç†"

  # 7. å›½å†…åŸŸåå’ŒIPåœ°å€ç›´è¿
  - "GEOIP,LAN,ğŸ¯ å…¨çƒç›´è¿"
  - "GEOSITE,cn,ğŸ¯ å…¨çƒç›´è¿"
  - "GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿"


  # 8. æœ€ç»ˆè§„åˆ™ï¼šæ‰€æœ‰å…¶ä»–æµé‡ç›´è¿ (é»‘åå•æ¨¡å¼)
  - "MATCH,ğŸ¯ å…¨çƒç›´è¿"