proxies:
  # åœ¨æ­¤å¤„æ·»åŠ æ‰‹å·¥ç²¾é€‰çš„èŠ‚ç‚¹
  # æ ¼å¼ç¤ºä¾‹:
  # - {name: 'Manual-Node-01', type: ss, server: 1.2.3.4, port: 8888, cipher: aes-256-gcm, password: 'password'}
  - {name: 'ğŸŒŸFrance_None_hysteria_81', type: hysteria, server: 62.210.196.68, port: 26691, auth_str: 'dongtaiwang.com', alpn: [h3], sni: apple.com, skip-cert-verify: true, up: '11 Mbps', down: '55 Mbps', protocol: udp}