name: Clean and Merge

on:
  schedule:
    - cron: '5 * * * *'
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/merge.yml'
      - 'src/freenodes-clashfree-ss-cleaner-sys.py'
      - 'src/merge.py'
      - 'src/ip_blocklist.txt'
      - 'src/sources.json'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 执行 - Cleaner - freenodes clashfree
        run: python ./src/freenodes-clashfree-ss-cleaner-sys.py

      - name: 执行 - Merge
        run: python ./src/merge.py

      - name: 检查 merge.yml 文件是否有变动
        id: check_changes
        run: |
          git add s/merge.yml
          if git diff --staged --quiet; then
            echo "merge.yml 文件没有变动。"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "merge.yml 文件有更新。"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: 执行 - Clash to v2rayN
        if: steps.check_changes.outputs.has_changes == 'true'
        run: python ./src/clash_to_v2rayn.py ./s/merge.yml

      - name: 提交更改
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Auto-update: $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin dev

      - name: 发送成功通知到 Telegram
        if: success() 
        # if: success() && steps.check_changes.outputs.has_changes == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ✅ *任务成功*
            **仓库**: `${{ github.repository }}`
            **更新内容**: `s/merge.yml` 文件已更新并推送。
            **提交信息**: `Auto-update: $(date '+%Y-%m-%d %H:%M:%S')`
            查看运行日志

      - name: 发送失败通知到 Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ❌ *任务失败*
            **仓库**: `${{ github.repository }}`
            请检查 Actions 日志以获取详细错误信息。
            查看运行日志