name: Clean and Merge

on:
  schedule:
    - cron: '5 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/merge.yml'
      - 'src/freenodes-clashfree-ss-cleaner-sys.py'
      - 'src/merge.py'
      - 'src/ip_blocklist.txt'
      - 'src/sources.json'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 执行 - Cleaner - freenodes clashfree
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python ./src/freenodes-clashfree-ss-cleaner-sys.py

      - name: 执行 - Merge
        run: python ./src/merge.py

      - name: 检查 merge.yml 文件是否有变动
        id: check_changes
        run: |
          git add s/merge.yml
          if git diff --staged --quiet; then
            echo "merge.yml 文件没有变动。"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "merge.yml 文件有更新。"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: 执行 - Clash to v2rayN
        if: steps.check_changes.outputs.has_changes == 'true'
        run: python ./src/clash_to_v2rayn.py ./s/merge.yml

      - name: 获取当前时间
        id: get_time
        run: echo "commit_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: 提交更改
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Update: ${{ steps.get_time.outputs.commit_time }}"
          git push origin dev

      - name: 发送成功通知到 Telegram
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ✅ *任务成功*
            **Time**: `${{ steps.get_time.outputs.commit_time }}`
            **消息内容**: `${{ github.repository }} - 节点列表已更新`

      # - name: 发送失败通知到 Telegram
      #   if: steps.check_changes.outputs.has_changes == 'false'
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_CHAT_ID }}
      #     token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #     format: markdown
      #     message: |
      #       ❌ *任务失败*
      #       **Time**: `${{ steps.get_time.outputs.commit_time }}`
      #       **消息内容**: `${{ github.repository }} - 没有更新的节点`

      - name: 发送异常通知到 Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            ⚠️ *任务异常*
            **Time**: `${{ steps.get_time.outputs.commit_time }}`
            **消息内容**: `${{ github.repository }} 任务发生异常，请检查`